#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <unistd.h>
#include <sys/wait.h>
#include <cstdlib>
#include <cstdio>
#include "builtins.h"

using namespace std;

/**
 * Parse args from string
 * 
 * @param line string of user input
 * @return Vector of strings generated by splitting on whitespace
 */
vector<string> get_args(string &line) {
    istringstream iss(line);
    vector<string> args;
    
    for (string arg; iss >> arg; ) {
        args.push_back(arg);
    }
    return args;
}

void shell_loop() {
    string line; // Store the current line of input
    int status = 0; // Store the status of the last command

    while (true) {
        cout << "\033[34m" << ">> " << flush;
        getline(cin, line);
        cout << "\033[0m" << flush;
        vector<string> args = get_args(line);
        if (args.empty()) {
            continue;
        } 
        if (args[0] == "exit") {
            break;
        }
        if (args[0] == "cd") {
            status = change_directory(args);
            continue;
        }

        status = execute_command(args);
        cout << "\033[0m";
    }
    
}

int main() {

    // Initialize shell config

    // Redirect to bin in this repo for custom commands
    const char* old_path = getenv("PATH");
    string new_path = string("./cppshell/bin:") + (old_path ? old_path : ""); // prepend custom bin to PATH w/o editing it
    setenv("PATH", new_path.c_str(), 1);

    // Main loop
    shell_loop();
    
    // Clean up 

    // Return success
    return 0;
}